### ISSUE TITLE
can't get modbus working

### ISSUE THREAD

**Issue by andrasg** [gregewing/apcupsd#7]
I am trying to get usb-modbus communication working on an APC SMT1500i (ID=18, firmware 9.3), but seemingly it won't connect:

```
root@a0689fdd2dae:/# apcaccess status
APC      : 001,018,0450
DATE     : 2023-06-06 20:43:12 +0200  
HOSTNAME : a0689fdd2dae
VERSION  : 3.14.14 (31 May 2016) debian
UPSNAME  : smt1500i
CABLE    : USB Cable
DRIVER   : MODBUS UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 2023-06-06 20:43:00 +0200  
STATUS   : COMMLOST 
MBATTCHG : 5 Percent
MINTIMEL : 5 Minutes
MAXTIME  : 0 Seconds
NUMXFERS : 0
TONBATT  : 0 Seconds
CUMONBATT: 0 Seconds
XOFFBATT : N/A
STATFLAG : 0x05000100
END APC  : 2023-06-06 20:43:12 +0200  
```

I have enabled modbus on the device's menu. Could it be that the code is not build with modbus support? Maybe hitting this? https://marc.info/?l=apcupsd-users&m=148305369513924&w=2

**Comment by andrasg** [comment]
Interestingly, if I install apcupsd on the host itself, I can get modbus communication working with the same `apcupsd.conf`. Looks like it's not enough to pass `/dev/usb/hiddev0` to the container when trying to use modbus...?

**Comment by gregewing** [comment]
Quite possibly the Ubuntu package I use in the docker is not compiled with modbus, or some dependent modbus kernel module or software subsystem.

I’ll investigate it in the next few days. Sorry, quite busy with work at the moment.



Thanks and Regards
Greg Ewing
________________________________

**Comment by gregewing** [comment]
Hi, so having a look at this now, 

I suspect that it is because apcuspd is not compiled with modbus included in the package that I use, but I have not way to prove that or test it out, so I will need your help.  I'll investigate further and look into compiling the apcupsd software at the point where I build the container and see if I can add in either one or the other or both of the modbus compile time options, though my preference woudl be to use a stock package...

Can you please tell me a little about your **host** system, such as the specific version of the operating system, and if possible the specific package for apcupsd that is installed ?  

maybe something like this ?


# apt list --installed  | grep apcupsd

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

apcupsd/jammy,now 3.14.14-3.1build1 amd64 [installed]



# cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by andrasg** [comment]
Happy to support! Are you suspecting that the binary version I am installing on my host contains modbus support while the one you install in the docker image doesn't?

apcupsd version installed:
```
pi@ha-rpi:~ $ apt list --installed | grep apcupsd

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

apcupsd-doc/stable,stable,now 3.14.14-3.1 all [installed,automatic]
apcupsd/stable,now 3.14.14-3.1 arm64 [installed]
```

OS properties:
```
pi@ha-rpi:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

I tried compiling my own copy of apcupsd using the `--enable-modbus-usb` flag but could not figure out how the make system works, always got into some weird compilation error.

**Comment by gregewing** [comment]
yes, that's my thinking.  the container uses Ubuntu, mostly because its what I'm most familiar with.  

I ahve a few options to fix this which I'll investigate independently of eachother.  From initial investigations, it looks like the package from Ubuntu may not be built with the modbus modules included, despite this being the default configuration.  That said, there is no direct build candidate for Ubuntu in the source code, or in the documentation, so whatever Canonical have done it's 'custom'.   Maybe someone thougth to explicitly exclude modbus...  or as I see from building it in a container, possibly the dependent USB Drivers for Modbus-USB...

In the short run it might be more sensible to publics a replacement container using a Debian Base image. 

I'll have a poke at both options and let you know when I'm ready for you to test.

**Comment by gregewing** [comment]
I've created a container using debian:bullseye (latest) as the base image. which looks like its an exact match to your host.  Can you give it a try please ?  it should be a drop-in replacement for your existing container, literally the only thing i changed was the base image, everything else is unchanged from the Ubuntu based image.   I've done same rudimentary testing and I at least get the data from my UPS coming up in apcaccess.  Though I've not tested any of the doshutdown capabilities or anything like that.

docker pull gregewing/apcupsd:testing

If you're still having problems, then its either the container configuration, or something more fundamental that I'm not likely to be able to help with.

Some things to think about: 

Do you have any diagnostics that you can perform to check that modbus is being passed through correctly over USB to the container?   I briefly read about issues with modbus, which resulted in the code being changed to support modbus over USB within the apcupsd software.

**Comment by andrasg** [comment]
Tried with the testing image, result is the same, no communication.

```
root@f0a9d36dc902:/# apcaccess 
APC      : 001,018,0450
DATE     : 2023-06-08 12:56:30 +0200  
HOSTNAME : f0a9d36dc902
VERSION  : 3.14.14 (31 May 2016) debian
UPSNAME  : smt1500i
CABLE    : USB Cable
DRIVER   : MODBUS UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 2023-06-08 12:56:22 +0200  
STATUS   : COMMLOST 
MBATTCHG : 5 Percent
MINTIMEL : 5 Minutes
MAXTIME  : 0 Seconds
NUMXFERS : 0
TONBATT  : 0 Seconds
CUMONBATT: 0 Seconds
XOFFBATT : N/A
STATFLAG : 0x05000100
END APC  : 2023-06-08 12:56:46 +0200  
```

I think modbus protocol support in docker would need some other things to be passed to the container, but could not figure it out.

**Comment by andrasg** [comment]
Ha! I think I figured it out. I made the container privileged. Now it works with both `latest` and `testing`. I don't even need to pass in `/dev/usb/hiddev0` to the container.

```
root@a8b2096804db:/# apcaccess 
APC      : 001,039,0908
DATE     : 2023-06-08 13:08:36 +0200  
HOSTNAME : a8b2096804db
VERSION  : 3.14.14 (31 May 2016) debian
UPSNAME  : APCUPS
CABLE    : USB Cable
DRIVER   : MODBUS UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 2023-06-08 13:08:30 +0200  
MODEL    : Smart-UPS 1500
STATUS   : ONLINE 
LINEV    : 226.0 Volts
LOADPCT  : 26.0 Percent
LOADAPNT : 24.0 Percent
BCHARGE  : 100.0 Percent
TIMELEFT : 50.0 Minutes
MBATTCHG : 5 Percent
MINTIMEL : 5 Minutes
MAXTIME  : 0 Seconds
OUTPUTV  : 226.0 Volts
DWAKE    : 0 Seconds
DSHUTD   : 0 Seconds
ITEMP    : 32.4 C
BATTV    : 27.0 Volts
LINEFREQ : 50.0 Hz
OUTCURNT : 1.59 Amps
NUMXFERS : 0
TONBATT  : 0 Seconds
CUMONBATT: 0 Seconds
XOFFBATT : N/A
SELFTEST : OK
STATFLAG : 0x05000008
MANDATE  : 2017-07-02
SERIALNO : 3S1726X07506
BATTDATE : 2023-06-15
NOMOUTV  : 230 Volts
NOMPOWER : 1000 Watts
NOMAPNT  : 1500 VA
FIRMWARE : UPS 09.3 / 00.4
END APC  : 2023-06-08 13:08:38 +0200  
```

Would be great to know what exactly is needed from the host os to make modbus comms work.

**Comment by gregewing** [comment]
Cool, I'm glad you got it working.

It's a bit of a shame that the container needs privileged mode though.  I guess with the right configuration of ssh keys and a script, one could remotely execute shutdown on the host from within the container.  I've certainly done similar in the past with widely distributed systems, where self management is necessary.   But for now the in-built systems within apcupsd are sufficient for most peoples purposes, and running in privileged mode does not seem to concern anyone, not that I've heard at least, not in relation to this container, though there is a clear risk in running with privileged mode enabled.

**Comment by andrasg** [comment]
Yeah, agree. Thanks for helping in diagnosing!
